### ISSUE TITLE
G drive link missing 

### ISSUE THREAD

**Issue by pr3m-kamble** [codescalper/books.10xeng#1]
app/books/sem3/page.tsx. maths 3 gdrive link is missing 
![Screenshot_2024-07-14-11-50-46-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/6d34b852-6fe3-4990-b1f9-194b579f88e8)

**Comment by pr3m-kamble** [comment]
If we click on maths3 link it redirect to DSGT

**Comment by codescalper** [comment]
@pr3m-kamble fixed 

Do share the website with others :)
